apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv 
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec: 
  rules: 
    - host: posts.com
      http:
        paths:
          - path: /posts/create
            pathType: Prefix
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 4000
                  # C:\Windows\System32\drivers\etc
          - path: /posts
            backend:    
              serviceName: query-srv
              servicePort: 4002
          - path: /posts/?(.*)/comments 
              #  ?(.*) is the regex for {id} because ingress does not supp. variable stuff like {id}
            backend:
              serviceName: comments-srv
              servicePort: 4001
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000

