apiVersion: apps/v1
kind: Deplyoment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLables: 
      app: posts
  template:
    metadata: 
      labels:
        app: posts
    spec: 
      containers: 
        - name: posts
          image: dhansdokker/posts